<?php

namespace common\modules\team\models;

use Yii;

/**
 * This is the model class for collection "board".
 *
 * @property \MongoDB\BSON\ObjectID|string $_id
 * @property mixed $name
 * @property mixed $cover_img
 * @property mixed $tag
 * @property mixed $discription
 */
class Board extends \yii\mongodb\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function collectionName()
    {
        return ['oa', 'board'];
    }

    /**
     * @inheritdoc
     */
    public function attributes()
    {
        return [
            '_id',
            'name',
            'cover_img',
            'tag',
            'sequence',
            'discription',
        ];
    }

    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_CREATE] = ['name', 'cover_img', 'tag', 'sequence', 'discription'];
        $scenarios[self::SCENARIO_UPDATE] = ['name', 'cover_img', 'tag', 'sequence', 'discription'];
        return $scenarios;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['_id','name', 'cover_img', 'tag','sequence', 'discription'], 'safe'],
            //['id', 'targetAttribute' => '_id',],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            '_id' => 'ID',
            'name' => 'Name',
            'cover_img' => 'Cover Img',
            'tag' => 'Tag',
            'discription' => 'Discription',
        ];
    }

    public function load($data, $formName = null)
    {
        $result = parent::load($data, $formName); // TODO: Change the autogenerated stub
        if(is_string($this->tag)){
            $this->tag = json_decode($this->tag,true)?:$this->tag;
        }

        return $result;

    }

    /*public function findOne($id){
        self::find()
    }*/
}
